add support for govcloud in iam modules
18F/identity-terraform pull request #132
Opened 2022-05-10 22:23 UTC by rbogle

AWS arns are unique for different partitions: 

- commercial accounts : "aws"
- govcloud: "aws-us-gov"
etc

This PR adjusts the arns in 

- Iam_assumegroup
- Iam_masterassume
- iam_masterusers

to be passed a different partition value if needed, but defaulting to the commercial 'aws' partition.

2022-05-10 22:27 UTC, pauldoomgov approved these changes
Thanks for the contribution!   Looks good!

2022-05-10 22:28 UTC, bleachbyte requested changes
Please adjust the formatting for the `variable` blocks such that the lines are aligned with the `=` marks, e.g.:

```
  description = "which aws partition this is deployed in"
  type        = string
  default     = "aws"
```

We haven't yet attached a `terraform fmt` lint check to **_this_** repo, but as said check is in other downstream repos, this formatting will need to be in place first.

2022-05-11 00:58 UTC, rbogle commented
Re-formatted! Thx!

2022-05-11 15:57 UTC, bleachbyte approved these changes
That'll work! 🚢

2022-05-11 18:57 UTC, rbogle commented
@pauldoomgov or @bleachbyte
how does this get merged?

2022-05-11 19:17 UTC, bleachbyte commented
And here I thought we opened that up to folks once things were 👍 'd -- I'll take care of this for ya.

2022-05-11 19:17 UTC, merged